app/[locale]/dashboard/page.tsx
components/ui/blocks/dialog.tsx
components/ui/blocks/drawer.tsx
prisma/seed.ts

this pr fixes a few type errors.

chore: fix type errors

---

.github/workflows/build-deploy.yml
.github/workflows/validate.yml

this pr provides required github variables and secrets to the build steps in github ci/cd workflows.

ci: provide required github variables and secrets to ci/cd workflows

---

.github/workflows/validate.yml
app/[locale]/dashboard/reports/[year]/countries/[code]/page.tsx

this pr provides required environment variables to the e2e test step in github ci.

ci: provide required env vars to e2e test step in ci

---

config/auth.config.ts
next.config.js

this updates redirects and rewrites.

fix: update redirects and rewrites

---

app/[locale]/(index)/page.tsx
app/[locale]/dashboard/admin/page.tsx
app/[locale]/imprint/page.tsx
app/[locale]/privacy-policy/page.tsx
app/[locale]/terms-of-use/page.tsx
components/app-footer.tsx
components/auth-controls.tsx
components/auth-user-menu.tsx
components/forms/contributions-form-content.tsx
components/forms/institutions-form-content.tsx
components/forms/outreach-reports-form-content.tsx
components/forms/service-reports-form-content.tsx
components/page-lead-in.tsx
messages/de.json
messages/en.json

this pr improves lead-in text styles, and adds a skeleton for the admin dashboard page. also fills in missing contextual help texts.

style: improve lead-in texts

---

app/[locale]/dashboard/reports/[year]/countries/[code]/edit/[step]/page.tsx
components/forms/contributions-form-content.tsx

include jrc in relevant contribution roles instead of dco on contributions form step.

fix: include jrc in relevant contribution roles instead of dco

---

components/forms/report-summary.tsx
package.json

this uses EUR currency number format for operational cost numbers.

fix: use currency number format for operational cost

---

components/forms/report-summary.tsx

this fixes the currency number formatter in async server component.

fix: use async number formatter

---

app/[locale]/dashboard/reports/[year]/countries/[code]/edit/[step]/page.tsx
components/forms/contributions-form-content.tsx
components/forms/event-report-form-content.tsx
components/forms/institutions-form-content.tsx
components/forms/outreach-reports-form-content.tsx
components/forms/projects-funding-leverages-form-content.tsx
components/forms/publications-form-content.tsx
components/forms/publications-form.tsx
components/forms/research-policy-developments-form-content.tsx
components/forms/service-reports-form-content.tsx
components/forms/software-form-content.tsx

this updates some intro texts to forms.

fix: update lead-in texts to forms

---

components/admin/institutions-form-content.tsx
lib/actions/update-institution.ts
lib/data/institution.ts
prisma/dbml/schema.dbml
prisma/ingest.ts
prisma/schema.prisma

this adds body and role enums to the data model, and consistently camelcases field names (ror and orcid instead of ROR and ORCID).

fix: avoid uppercase field names, add body and role enums

---

app/[locale]/dashboard/admin/page.tsx
app/[locale]/dashboard/admin/persons/page.tsx
components/admin/institutions-form-content.tsx
components/admin/persons-form-content.tsx
lib/actions/update-person.ts
lib/data/person.ts
messages/de.json
messages/en.json

this adds an admin dashboard page to edit person details.

feat: add admin dashboard for persons

---

.vscode/settings.json
content/documentation/guidelines.mdx
next.config.js

this adds a documentation page for definitions and guidelines.

docs: add guidelines docs

---

app/[locale]/dashboard/reports/[year]/countries/[code]/edit/[step]/page.tsx
components/forms/event-report-form-content.tsx
components/forms/software-form-content.tsx

this updates the intro texts and help texts.

docs: update intro texts

---

lib/db/ingest-data-from-sshomp.ts
prisma/create-initial-entries-from-sshomp.ts

this handles the case of multiple reviewers on dariah resources when importing data from ssh open marketplace.

fix: handle multiple reviewers in sshomp dariah resources

---

app/[locale]/dashboard/admin/page.tsx
app/[locale]/dashboard/admin/software/page.tsx
components/admin/institutions-form-content.tsx
components/admin/persons-form-content.tsx
components/admin/software-table-content.tsx
components/ui/table.tsx
lib/actions/admin/create-software.ts
lib/actions/admin/delete-software.ts
lib/actions/admin/update-software.ts
lib/data/person.ts
lib/data/software.ts
lib/db/ingest-data-from-sshomp.ts
messages/de.json
messages/en.json
prisma/create-initial-entries-from-sshomp.ts
tailwind.config.ts

this adds a new admin dashboard page to create, update, and delete software entries.

feat: software admin dashboard

---

app/[locale]/dashboard/admin/page.tsx
app/[locale]/dashboard/admin/services/page.tsx
components/admin/services-table-content.tsx
lib/actions/admin/create-service.ts
lib/actions/admin/create-software.ts
lib/actions/admin/delete-service.ts
lib/actions/admin/update-service.ts
lib/data/service.ts
lib/get-form-data.ts
lib/schemas/utils.ts
messages/de.json
messages/en.json

this adds a new page to the admin dashboard for creating, editing, and deleting services.
there is currently an issue with updating institutions/roles, which needs to be fixed in a follow-up.

feat: add services admin dashboard

---

lib/data/service.ts

this fixes updating the explicit service-institution join table in the service admin dashboard.

fix: fix updating service institution roles

---

app/[locale]/dashboard/admin/institutions/page.tsx
app/[locale]/dashboard/admin/page.tsx
app/[locale]/dashboard/admin/persons/page.tsx
app/[locale]/dashboard/admin/services/page.tsx
app/[locale]/dashboard/admin/software/page.tsx
app/[locale]/dashboard/admin/users/page.tsx

this improves data loading for admin dashboard pages by requesting data concurrently. also adds some minor style improvements to the admin dashboard overview page.

perf: admin page data loading

---

app/[locale]/dashboard/admin/outreach/page.tsx
app/[locale]/dashboard/admin/page.tsx
components/admin/outreach-table-content.tsx
lib/actions/admin/create-outreach.ts
lib/actions/admin/delete-outreach.ts
lib/actions/admin/update-outreach.ts
lib/data/outreach.ts
messages/de.json
messages/en.json

this adds a new admin dashboard page to create, edit, and delete outreach entries.

feat: add outreach admin dashboard page

---

app/[locale]/dashboard/admin/institutions/page.tsx
app/[locale]/dashboard/admin/outreach/page.tsx
app/[locale]/dashboard/admin/page.tsx
app/[locale]/dashboard/admin/persons/page.tsx
app/[locale]/dashboard/admin/reports/page.tsx
app/[locale]/dashboard/admin/services/page.tsx
app/[locale]/dashboard/admin/software/page.tsx
app/[locale]/dashboard/admin/sshomp/page.tsx
app/[locale]/dashboard/admin/users/page.tsx
components/admin/reports-table-content.tsx
lib/data/report.ts

this adds a new admin dashboard page for reports. reports are not editable, this is mainly to be able to see comments.

feat: add reports admin dashboard

---

app/[locale]/dashboard/reports/[year]/countries/[code]/edit/[step]/page.tsx
components/admin/reports-table-content.tsx
components/delay.tsx
components/loading-indicator.tsx

this improves the comments column in the admin dashboard reports page.

feat: improve report comments column

---

components/admin/services-table-content.tsx

this fixes a crash in service table column sorting for null values, and makes more columns sortable.

fix: fix service table column sorting, make more columns sortable

---

components/admin/services-table-content.tsx
components/admin/software-table-content.tsx

this adds some basic statistics about service and software in the database to the admin dashboard pages.

feat: add statistics to service and software admin dashboard page

---

app/[locale]/dashboard/admin/institutions/page.tsx
app/[locale]/dashboard/admin/outreach/page.tsx
app/[locale]/dashboard/admin/persons/page.tsx
app/[locale]/dashboard/admin/reports/page.tsx
app/[locale]/dashboard/admin/services/page.tsx
app/[locale]/dashboard/admin/software/page.tsx
app/[locale]/dashboard/admin/sshomp/page.tsx
app/[locale]/dashboard/admin/users/page.tsx
components/forms/outreach-reports-form-content.tsx
lib/actions/admin/create-outreach.ts
lib/actions/create-outreach.ts
lib/data/outreach.ts

this add a new create-outreach button and dialog to the outreach report page.

fix: add create-outreach dialog to report page

---

components/admin/services-table-content.tsx
components/ui/blocks/date-input-field.tsx
components/ui/blocks/number-input-field.tsx
components/ui/blocks/required-indicator.tsx
components/ui/blocks/select-field.tsx
components/ui/blocks/text-area-field.tsx
components/ui/blocks/text-input-field.tsx

this adds an asterisk indicator to the labels of required form fields.

feat: add asterisk indicator on required form fields

---

prisma/create-country-ids-from-sshomp.ts

this adds the marketplace id for clariah-es to the country-id script.

fix: add clariah-es marketplace id

---

components/admin/institutions-table-content.tsx
components/admin/outreach-table-content.tsx
components/admin/persons-table-content.tsx
components/admin/reports-table-content.tsx
components/admin/software-table-content.tsx
components/admin/users-table-content.tsx

this makes more table colummns in the admin dashboard pages sortable.

feat: make more admin dashboard table columns sortable

---

lib/calculate-operational-cost.ts

this changes the operational cost calculation to no longer use `service.size` for determining a service_s size, but the "visits" kpi in the service report.
for the thresholds for "small"/"medium"/"large", see https://github.com/DARIAH-ERIC/dariah-unr/issues/143

fix: use service kpi for calculating service size in operational cost calculation

---

components/forms/event-report-form.tsx
components/forms/outreach-reports-form.tsx
components/forms/projects-funding-leverages-form.tsx
lib/actions/update-event-report.ts
lib/actions/update-software.ts
lib/data/software.ts
lib/schemas/report.ts

this fixes pre-populating the comments textarea field with saved comments in the event-report and outreach-report forms.

fix: correctly display saved comments in event-report and outreach-report forms

---

lib/actions/admin/create-user.ts
lib/data/user.ts

this fixes the "create user" form in the admin dashboard.

fix: allow creating user via admin dashboard

---

app/[locale]/dashboard/admin/page.tsx
app/[locale]/dashboard/admin/statistics/[year]/page.tsx
components/admin/statistics-content.tsx
components/forms/publications-form.tsx
lib/data/stats.ts
lib/schemas/dashboard.ts
messages/de.json
messages/en.json

this adds a new page to the admin dashboard, which displays basic statistics for the current reporting period.

feat: add statistics page to admin dashboard

---

Dockerfile

this pr works around an issue with corepack integrity keys.

ci: work around corepack integrity key issue

---

Dockerfile

build: work around prisma 5.x not finding ssl on newer alpine linux verions

---

app/api/v1/countries/route.ts
app/api/v1/institutions/route.ts
app/api/v1/persons/route.ts
app/api/v1/working-groups/route.ts

this pr adds public api endpoints for countries, institutions, persons, and working groups.
the person endpoint currently only returns names - needs legal advice if it is ok to return additional personal data.

feat: add public api endpoints

---

components/forms/contributions-form.tsx
components/forms/report-summary.tsx
lib/calculate-operational-cost.ts
lib/data/contributions.ts

@stefanprobst could please have a quick look, if this doesn't cause any follow-up issues for calculations?

fix: filter contributions by year

---

components/admin/institutions-table-content.tsx
components/admin/persons-table-content.tsx

fix: use correct labels

---

lib/db/ingest-data-from-sshomp.ts

refactor: ingest accessibleAt url(s)

---

components/admin/institutions-table-content.tsx
components/ui/table.tsx

feat: allow table filtering by country

---

components/admin/outreach-table-content.tsx
components/admin/reports-table-content.tsx
components/admin/services-table-content.tsx
components/admin/software-table-content.tsx
components/admin/users-table-content.tsx

feat: add country filter to admin tables

---

prisma/schema.prisma

#218
merging batch of data model changes to one branch

Added WGReport table

---

components/admin/institutions-table-content.tsx
e2e/tests/pages/imprint.test.ts

feat: allow selecting multiple institution types

---

app/[locale]/dashboard/admin/countries/[code]/page.tsx
app/[locale]/dashboard/admin/countries/layout.tsx
app/[locale]/dashboard/admin/countries/page.tsx
app/[locale]/dashboard/admin/page.tsx
components/admin/contributions-table-content.tsx
components/admin/country-dashboard-content.tsx
components/admin/country-filter.tsx
components/admin/institutions-table-content.tsx
components/admin/services-table-content.tsx
components/admin/software-table-content.tsx
lib/actions/admin/update-country.ts
lib/data/country.ts
messages/en.json

regarding: #158
- adds form to update country data
- adds tables for country (institution, contribution, service, software)

feat: country view for admin
