prisma/dbml/schema.dbml
prisma/ingest.ts
prisma/schema.prisma

this adds an ingest script which fetches data from the legacy baserow database, and populates the postgres db with it.
a couple of issues, which should be addressed in a follow-up:
- the service size field is mandatory, but not provided in the baserow table, so we default to "small" for now.
- the `InstitutionToService` join table needs to be populated manually, because the baserow service table does not specify institution ids.
- the "website" baserow table does not have a `name` field. for now, we duplicate `url`.

feat: add ingest script to fetch data from baserow database

---

prisma/schema.prisma

this pr adds a event-size model to the data schema, which is currently missing for the annual value calculation.

fix: add event-size model for annual value calculation

---

prisma/dbml/schema.dbml
prisma/schema.prisma

this pr adds a new table to the data model for annual value per outreach type. this is used only for calculation.

fix: add table for outreach value per outreach type

---

components/forms/outreach-reports-form-content.tsx
components/forms/service-reports-form-content.tsx

this pr pre-populates kpi fields for service and outreach, if none have been added before.

feat: add pre-populated kpi fields

---

app/[locale]/dashboard/reports/[year]/countries/[code]/edit/[step]/page.tsx
app/[locale]/dashboard/reports/[year]/countries/[code]/page.tsx
app/[locale]/documentation/[id]/page.tsx
app/[locale]/privacy-policy/page.tsx
app/[locale]/terms-of-use/page.tsx
app/not-found.tsx
components/app-footer.tsx
components/auth-controls.tsx
components/code-block.tsx
components/forms/contributions-form.tsx
components/forms/event-report-form-content.tsx
components/forms/event-report-form.tsx
components/forms/institutions-form.tsx
components/forms/outreach-reports-form-content.tsx
components/forms/outreach-reports-form.tsx
components/forms/projects-funding-leverages-form-content.tsx
components/forms/projects-funding-leverages-form.tsx
components/forms/publications-form.tsx
components/forms/research-policy-developments-form-content.tsx
components/forms/research-policy-developments-form.tsx
components/forms/service-reports-form-content.tsx
components/forms/service-reports-form.tsx
components/forms/software-form.tsx
lib/actions/update-projects-funding-leverages.ts
lib/actions/update-service-reports.ts
messages/de.json
messages/en.json

this pr adds new privacy-policy (source: https://github.com/DARIAH-ERIC/dariah-unr/discussions/13) and terms-of-use pages (source: https://github.com/DARIAH-ERIC/dariah-unr/discussions/14), and adds intro text to form steps (sources: https://github.com/DARIAH-ERIC/dariah-unr/discussions/15).
in the future, it would be good to make these texts editable via keystatic cms.

feat: add privacy-policy and terms-of-use pages, as well as lead-in text for form steps

---

middleware.ts
package.json

this pr disables the no-unused-vars eslint rule temporarily.

chore: lint

---

vitest.config.ts

this pr adds the `passWithNoTests` config option to `vitest`.

chore: pass unit test step when no tests are found

---

.github/workflows/build-deploy.yml

this fixes a typo in the github workflow which messed up the token.

ci: fix github token

---

.github/workflows/build-deploy.yml

this switches the deployment ci/cd job to use a different workflow, which should be identical but depends on a different set on variables

ci: use alternative workflow

---

.vscode/app.code-snippets
app/[locale]/dashboard/reports/[year]/countries/[code]/edit/[step]/page.tsx
app/[locale]/dashboard/reports/[year]/countries/[code]/page.tsx
app/[locale]/documentation/[id]/page.tsx
app/[locale]/layout.tsx
lib/get-report-years.ts
package.json

this adds supported report years (from 2022 to the current year minus one, which represents the most recent reporting period) to dynamic route params. also disables `dynamicParams = false` for now, since the next.js behavior differs between dev and prod.

fix: add report year to dynamic route params

---

app/[locale]/contact/page.tsx
app/[locale]/dashboard/reports/[year]/countries/[code]/edit/[step]/page.tsx
components/contact-form-content.tsx
components/contact-form.tsx
components/forms/confirmation-form.tsx
components/forms/report-summary.tsx
components/forms/summary.tsx
lib/schemas/email.ts

this adds a link to the contact form to the report summary page, allows navigating back to previous form steps from the summary page, and duplicates the report summary on the confirmation form step.

feat: add link to contact form to summary page

---

app/[locale]/dashboard/reports/[year]/countries/[code]/edit/[step]/loading.tsx

this displays a loading indicator when navigating between form steps, because this sometimes can take a bit (e.g. the publications step fetches from zotero), so we should ensure the ui does not feel laggy.

fix: display loading indicator between form steps

---

app/[locale]/dashboard/reports/[year]/countries/[code]/edit/[step]/page.tsx
components/forms/confirmation-form-content.tsx
components/forms/contributions-form-content.tsx
components/forms/contributions-form.tsx
components/forms/event-report-form-content.tsx

this adds help text to event report and contribution count fields, which indicates values filled in in the previous reporting period.

feat: add previous year data to event report and contribution count help text

---

lib/auth/config.ts

this sets `next-auth`'s `trustHost` setting to true, which should make `next-auth` use headers to correctly infer the hostname.

fix: trust host

---

app/api/keystatic/[...params]/route.ts

this fixes the port being set to the internal 3000 for cms oauth redirect uri.

fix: don't use internal port for cms oauth

---

app/keystatic/layout.tsx

this ensures cms translations (via react-aria/i18n) are available before the cms starts loading.

fix: ensure cms translations are available before cms loads

---

components/ui/number-input.tsx

this makes the number input a regular input field, because react-aria will manage validating input via js. setting the input type to "number" will lead to disappearing input for any value which needs a separator (i.e. above 999).

fix: don't set input type number on react aria number input field

---

lib/actions/contact.ts
lib/actions/update-contribution-end-date.ts
lib/actions/update-contributions.ts
lib/actions/update-event-report.ts
lib/actions/update-institutions.ts
lib/actions/update-outreach-reports.ts
lib/actions/update-projects-funding-leverages.ts
lib/actions/update-publications.ts
lib/actions/update-report-status.ts
lib/actions/update-research-policy-developments.ts
lib/actions/update-service-reports.ts
lib/actions/update-software.ts

this ensures that all server actions return a timestamp, which can be used to invalidate client views (via `key`).

fix: ensure all server actions return timestamps

---

app/[locale]/dashboard/reports/[year]/countries/[code]/edit/[step]/page.tsx

this adds a loading indicator while form data loads initially, which is especially important for the publications screen, because the zotero api can be slow.

fix: add loading indicator while form data loads initially

---

components/forms/projects-funding-leverages-form-content.tsx

this uses "day" granularity for date fields, instead of displaying time and timezone as well.

fix: use day granularity for day field

---

components/ui/form-error.tsx
components/ui/form-success.tsx
lib/data/contributions.ts
lib/data/country.ts
lib/data/institution.ts
lib/data/outreach.ts
lib/data/person.ts
lib/data/report.ts
lib/data/role.ts
lib/data/service.ts
lib/data/software.ts
lib/data/user.ts
lib/data/working-group.ts

this adds an explicit sort order to all `findMany` queries. note that we currently don't add any additional db indices.

fix: ensure responses have stable sort order

---

app/[locale]/dashboard/reports/[year]/countries/[code]/edit/[step]/page.tsx
components/forms/confirmation-form-content.tsx
components/forms/confirmation-form.tsx
prisma/dbml/schema.dbml
prisma/schema.prisma

this adds a new "national coordinator" user role, and disables the confirmation submit button for users with role "contributor".

feat: add national coordinator user role

---

prisma/ingest.ts

this uses the recently added "outreach name" column when ingesting data from baserow, instead of copying the url field.

fix: use new outreach name column in baserow ingest

---

components/forms/service-reports-form-content.tsx
components/forms/service-reports-form.tsx
components/forms/software-form-content.tsx
components/forms/software-form.tsx

this makes the add-software button link to ssh open marketplace, mirroring the behavior on the service-report page.
the source of truth for both software and services is the sshomp.

fix: make add-software button link to ssh open marketplace

---

app/[locale]/dashboard/admin/page.tsx
app/[locale]/dashboard/admin/sshomp/page.tsx
components/admin/sshomp-ingest-form-content.tsx
lib/actions/sshomp.ts
lib/db/ingest-data-from-sshomp.ts
messages/de.json
messages/en.json

this adds a new admin dashboard page to ingest software and services from the ssh open marketplace.
note that for this to work, sshomp actor ids need to be associated with countries in the unr database. this is what the `prisma/create-country-ids-from-sshomp.ts` script does.

feat: add dashboard button to ingest data from ssh open marketplace

---

content/documentation/data-model.mdx
content/documentation/guidelines.mdx
middleware.ts
next.config.js

this removes the redirects from `next.config.js`, which were not working, and adds a rewrite via middleware from `/documentation` to `/documentation/guidelines`.

docs: add middleware rewrite from /documentation to /documentation/guidelines

---

app/[locale]/(index)/page.tsx
components/app-header.tsx
middleware.ts

this removes the rewrite for `/documentation` pages, and instead directly links to the guidelines.

fix: directly link to guidelines instead of using rewrites

---

app/[locale]/dashboard/reports/[year]/countries/[code]/edit/[step]/page.tsx
content/documentation/guidelines.mdx

this updates the link to the google doc explaining how to add/update/delete items from the ssh open marketplace.

docs: update link to google doc

---

lib/data/service.ts
lib/data/software.ts

this changes the list of software and services to only include software with status "maintained" (i.e. not show "needs_review" software"), and only show services with status "live" (instead of those which are not marked as "discontinued").

fix: only list maintained software and live services

---

lib/db/ingest-data-from-sshomp.ts
prisma/create-initial-entries-from-sshomp.ts

this ensures we keep any software and services status when importing data from the ssh open marketplace. when creating new software, we set `status: "maintained"`, and `marketplaceStatus: "added_as_item"`, and when creating new services, we set `status: "live"` and `marketplaceStatus: "yes"`

fix: keep software and service status when updating from sshomp

---

readme.md

this fixes the link to the data model diagram in the readme.

docs: update data-model link in readme

---

app/[locale]/dashboard/admin/software/page.tsx

this removes the invalid dynamic page params on the software admin dashboard page, which caused the page to not render.

fix: remove unnecessary dynamic params on admin software page

---

config/auth.config.ts
e2e/tests/app/metadata.test.ts

this improves the e2e test for opengraph images, to (i) check the content-type, and (ii) ensure a `<meta>` tag is added.

test: check opengraph image content type in e2e test

---

components/loading-indicator.tsx
lib/use-id.ts
lib/use-labels.ts

this replaces `useLabels` from `@react-aria` with our own implementation in order to support the loading indicator component in server components. while `@react-aria/utils#useLabels` does not directly depend on client-only functionality, the way react-aria is currently bundled means it pulls in react context, which only works in client components.

fix: support loading indicator in server components

---

components/admin/pagination.tsx
components/admin/services-table-content.tsx
components/admin/software-table-content.tsx
components/admin/use-pagination.ts

this adds pagination to software and services admin dashboard tables. this should also improve the table lagginess a bit, which was pretty bad for the services table with ~350 rows. reconsider this once react-aria's table has virtualisation support. current page size is 50 rows, pagination state is currently not synced to url search params.

feat: add pagination to software and services admin dashboard tables

---

lib/db/ingest-data-from-sshomp.ts
prisma/create-initial-entries-from-sshomp.ts

this fixes a bug in the sshomp import script which reset the service size when updating an existing service.

fix: avoid re-setting service size on sshomp import

---

components/forms/institutions-form-content.tsx
lib/data/institution.ts

this adjusts the institutions reporting page to also list institutions of type "national_coordinating_institution", and adds a separate readonly textinput for institution type.
note that in most cases, "national_coordinating_institution" institutions will also be "partner_institution"s - but there is one edgecase in in switzerland where "Dasch" is a national coordinating institution but not (yet) a partner institution.

fix: display institution types, and list national_coordinating_institutions

---

lib/db/ingest-data-from-sshomp.ts
prisma/create-initial-entries-from-sshomp.ts

the script ingesting data from the ssh open marketplace did not correctly handle the case where an item had multiple "resource type" properties. these are used at ingest time to differentiate between software and service (the sshomp lists both as "tools and services" entity type).
we also add a log to list software items, which had previously been added to the services table.

fix: handle multiple resource types in sshomp ingest script

---

app/[locale]/dashboard/admin/statistics/[year]/page.tsx
components/admin/statistics-content.tsx

loading publications data from zotero can take a long time, especially on the admin statistics dashboard, because we cannot load data for all countries at once, but need to request each individually.
this wraps the publications count on the admin dashboard page in a suspense boundary, so other data can already be displayed while the zotero requests are still in flight.

fix: wrap publications in suspense boundary on admin statistics page

---

lib/zotero.ts

this adds a `limit=100` url search param when requesting publications from zotero (default is 25).
as a follow-up we should refactor this and (i) propertly read the pagination info returned from the zotero api via `Link` header [sic], and (ii) format citations outselves because (i.e. drop the `include=bib` param) because this slow down the zotero api response times dramatically.

fix: add limit search param to zotero request

---

app/[locale]/dashboard/reports/[year]/countries/[code]/edit/[step]/page.tsx
components/forms/event-report-form-content.tsx

x-ref #192
this changes the form-field label in the event-report form from "DARIAH commissioned event" to "Title of DARIAH commissioned event" so it is a bit clearer that this field accepts a string, not a number.

docs: clarify label for dariah-commissioned-events field

---

components/admin/statistics-content.tsx
components/forms/publications-form-content.tsx
components/forms/publications-form.tsx
components/forms/report-summary.tsx
lib/create-bibliography.ts
lib/parse-link-header.ts
lib/zotero.ts
package.json
pnpm-lock.yaml

this parses pagination info from the `Link` header returned with zotero api responses, so we can correctly fetch all items in a collection.
unfortunately, the zotero api is dead slow, so this is resulting in even more `TimeoutError`s than before.
one approach would be to format citations ourselves (with `citation-js`) instead of requesting formatted citations via `?include=bib`, which seems to affect query perf quite dramatically. it would also solve the incorrect sorting of entries by the zotero api, which does not correctly sort accented characters (i.e. É before A).
this is what this pr does: request data in csl-json format from zotero, and use citation-js to format a bibliography.
closes #198

fix: use pagination info from link header in zotero api response, and format csljson

---

components/admin/statistics-content.tsx
lib/zotero.ts

document that zotero may return strings as date parts, even though this is not allowed by csl-json.

docs: add comment about csl-json date fields in zotero [skip ci]

---

lib/zotero.ts

this ensures the zotero collections cache is revalidated after 5 minutes.

fix: revalidate zotero cache, set ttl to 5 minutes

---

app/[locale]/dashboard/reports/[year]/countries/[code]/edit/[step]/page.tsx
components/admin/statistics-content.tsx
components/error-boundary.tsx
lib/zotero.ts

this wraps UI which displays publications fetched from the zotero api, so we don't display a full error-page when the api request fails.
also adds cache for the api request for collections metadata, with a TTL of 60 minutes.

feat: wrap zotero api calls with error boundary

---

Dockerfile
components/admin/institutions-table-content.tsx
eslint.config.js
package.json
pnpm-lock.yaml
readme.md

this updates pnpm to the current major version (v10). also removes the npm integrity keys workaround from the Dockerfile which is no longer necessary.

build: update pnpm to v10

---

Dockerfile
entrypoint.sh

this installs the prisma cli globally in the docker image, in order to avoid installing it every time the container starts and the entrypoint script is executed.

build: install prisma cli globally in docker build context

---

styles/index.css

fix: ensure body is not scrollable when popover is open
